name: CI/CD Pipeline + Deployment

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run tests
      - name: Run tests
        run: npm test

      # 5️⃣ Docker login
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app:latest" .

      # 7️⃣ Tag image with commit SHA
      - name: Tag Docker image with commit SHA
        run: |
          docker tag "${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app:latest" "${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app:${{ github.sha }}"

      # 8️⃣ Push both tags to DockerHub
      - name: Push Docker image
        run: |
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app:latest"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app:${{ github.sha }}"

      # 9️⃣ Optional: Deploy to remote server
      - name: Deploy to server
        if: always()  # Only run if deployment is needed
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull "${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app:latest"
            docker stop nodejs-demo-app || true
            docker rm nodejs-demo-app || true
            docker run -d -p 3000:3000 --name nodejs-demo-app "${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app:latest"
