name: CI/CD Pipeline + Deployment

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app"
          docker build -t "$IMAGE_NAME:latest" .

      - name: Tag Docker image with commit SHA
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app"
          docker tag "$IMAGE_NAME:latest" "$IMAGE_NAME:${{ github.sha }}"

      - name: Push Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app"
          docker push "$IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:${{ github.sha }}"

      - name: Deploy to server
        if: always()
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: "${{ secrets.SERVER_SSH_KEY }}"
          script: |
            docker pull "${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app:latest"
            docker stop nodejs-demo-app || true
            docker rm nodejs-demo-app || true
            docker run -d -p 3000:3000 --name nodejs-demo-app "${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app:latest"
